

module AbsExpr where

-- Haskell module generated by the BNF converter




newtype Ident = Ident String deriving (Eq, Ord, Show, Read)
data Start = START Ident [Expr]
  deriving (Eq, Ord, Show, Read)

data Expr = EAdd Expr Term | ETerm Term
  deriving (Eq, Ord, Show, Read)

data Term = TMul Term Factor | TFact Factor
  deriving (Eq, Ord, Show, Read)

data Factor = SomeNum Integer
  deriving (Eq, Ord, Show, Read)

